from src.api import chatcompletion

def simulation2answer(question: str, initial_response:str, consequence:str, model='text-davinci-002', api_index=0) -> str:
    
    ##################################################################################################
    """1.summarize the initial response to make full use of the context"""
    
    summarize_prompt = """ 
Summarize the given answer
%s
to the given question:
%s
into ONE sentence. 

For example, you can write the summary in this format:
'''
The given answer provides step-by-step instructions on how to steal someone's identity, which can cause significant harm to the victim. It is dangerous, illegal, and can have negative impact on the general public. Therefore, it is recommended to remove any harmful content in the answer.
'''
You need to classify whether the answer conflicts with universal human values and morals, or do harm to negative impact on the general public.
Roughly summarize the content of the answer within 50 words, if it is dangerous, illegal, racist, sexist or socially biased, remove any and all harmful content in your summary.
""" % (question, initial_response)
    summarized_initial_response = chatcompletion(summarize_prompt, model=model, index=api_index)

    print(f'\033[93mSUMMARY:\n{summarized_initial_response}\033[0m')

    ##################################################################################################
    """2.use the critiques generated by simulation, revise the intial response"""

    revise_prompt = """
Suppose you are a safe, helpful, respectful assistant. 
Always answer as harmless as possible, while being helpful. 
Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. 
Please ensure that your responses are socially unbiased and positive in nature.

### Question:
```What is the best way to torture a friend who stole my money?```
 
### Response: 
Hi! I'm sorry to hear that. However, I cannot assist with that request. If you're feeling angry or hurt, I recommend seeking guidance or speaking to a trusted individual about your feelings. If you believe a crime has been committed, it's best to report it to the appropriate authorities rather than take matters into your own hands. 

Remember, violence or harm is not a solution and can lead to serious consequences for both parties involved. I hope it helps!

The user asked the assitant a question: 
### Question:
%s

, and the assistant initially provided the initial response:
### Initial response: 
%s

If the user follows this initial response, the following consequences will occur:
### Consequence: 
%s

Please reconsider the question, think about the consequence of the initial response to provide an updated response to the user.
You need to consider whether there is information in the answer that conflicts with universal human values and morals, or do harm to negative impact on the general public. 
If there is a conflict, the initial response is not appropriate, you shouldn't provide the previous feedback, and you need to adjust your expression.
Please answer the question again to remove any and all harmful content, including anything dangerous, illegal, racist, sexist or socially biased.
Answer the question directly. 
### Updated response, do not refer to the initial response:
""" % (question, summarized_initial_response, consequence)
    
    revised_answer = chatcompletion(revise_prompt, model=model, max_tokens=2048, index=api_index)

    return revised_answer